name: Build Action Release

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_call:
    inputs:
      ref:
        default: 'dev'
        type: string
      auto_update_file:
        default: 'canary.xml'
        type: string
      build_xpi:
        default: false
        type: boolean
    outputs:
      version:
        value: ${{ jobs.zip.outputs.version }}
      buildXPI:
        value: ${{ jobs.xpi.outputs.exist_xpi_file }}
    secrets:
      CRX_PRIVATE_KEY:
        required: true

jobs:
  build:
    name: Build dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: ${{ github.event_name == 'pull_request' && 1 || 0 }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '19'
          cache: yarn

      - run: yarn

      - run: yarn build
        continue-on-error: true

      - name: Upload Built to action
        uses: actions/upload-artifact@v4
        with:
          name: build-dist-folder
          path: dist
   crx:
    name: Build Crx (Chromium)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set name output
        id: auto_update_file
        env:
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}
        if: ${{ env.CRX_PRIVATE_KEY != ''  }}
        run: |
          USER_INPUT=${{ inputs.auto_update_file }}
          echo "value=${USER_INPUT:-"stable.xml"}" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        env:
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}
        if: ${{ env.CRX_PRIVATE_KEY != ''  }}
        with:
          name: build-dist-folder
          path: dist

      - name: Add update_url
        env:
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}
        if: ${{ env.CRX_PRIVATE_KEY != ''  }}
        run: echo $(jq '. |= .+ {"update_url":"https://pt-plugins.github.io/PT-Plugin-Plus/update/${{ steps.auto_update_file.outputs.value }}"}' dist/manifest.json) > dist/manifest.json

      - id: zip
        name: Build Zip With update_url
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        env:
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}
        if: ${{ env.CRX_PRIVATE_KEY != ''  }}
        with:
          extensionDir: 'dist'
          zipFilePath: 'extension.zip'

      - name: Build Crx
        env:
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}
        if: ${{ env.CRX_PRIVATE_KEY != ''  }}
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'extension.zip'
          crxFilePath: 'artifact/extension.crx'
          privateKey: ${{ secrets.CRX_PRIVATE_KEY }}
          updateXmlPath: artifact/${{ steps.auto_update_file.outputs.value }}
          updateXmlCodebaseUrl: https://github.com/pt-plugins/PT-Plugin-Plus/releases/download/v${{ steps.zip.outputs.extensionVersion }}/PT-Plugin-Plus-${{ steps.zip.outputs.extensionVersion }}.crx

      - name: Upload Built Crx to action
        env:
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}
        if: ${{ env.CRX_PRIVATE_KEY != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: dev-build-${{ steps.zip.outputs.extensionVersion }}-crx
          path: artifact/*